namespace com.zhusmelb.Util.Path
{
    public interface IPathConvension
    {
        /// <summary>
        /// Base path in which the executable locates.
        /// 
        /// This is usually the installation path of the executing assembly.
        /// </summary>
        string AppBase { get; }
        /// <summary>
        /// Data path in which data generated by application are stored
        /// 
        /// This is usually a directory under %ProgramData% folder.
        /// </summary>
        string AppDataBase { get; }
        /// <summary>
        /// Data path in which user speicific data are stored
        /// 
        /// This is usually a directory under %APPDATA% folder
        /// </summary>
        string UserDataBase { get; }

        string Log { get; }
        string Data { get; }
        string Cache { get; }

        string this[string name] { get; }
    }
}
